CREATE DATABASE IF NOT EXISTS go_chain;
USE go_chain;

-- 以下、作っておきたい初期設定を書いておくとビルド時に作成されるらしい

# CREATE TABLE IF NOT EXISTS users (
#     id          INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
#     name        VARCHAR(256) NOT NULL,
#     age         INT NOT NULL,
#     created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
#     updated_at  TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
# ) ENGINE=InnoDB DEFAULT CHARSET=utf8;